### PR TITLE
Fix most strong mode errors in lib/; LineSplitter issue remains

### LINKED ISSUE #32: Strong mode errors
(specifically on master, Dart at 1.23.0-dev.2.0):

```
$ dartanalyzer lib/ |sort |uniq
13 errors, 15 warnings and 31 hints found.
Analyzing lib...
[error] Invalid override. The type of 'ValueFuture.catchError' ('(Function, {test: (Object) → bool}) → Future<dynamic>') isn't a subtype of 'Future<T>.catchError' ('(Function, {test: (Object) → bool}) → Future<T>') at lib/src/value_future.dart:31:3 (strong_mode_invalid_method_override).
[error] Invalid override. The type of 'ValueFuture.then' ('<S>((T) → S, {onError: Function}) → Future<S>') isn't a subtype of 'Future<T>.then' ('<S>((T) → FutureOr<S>, {onError: Function}) → Future<S>') at lib/src/value_future.dart:33:3 (strong_mode_invalid_method_override).
[error] The argument type '(Process) → Future<int>' can't be assigned to the parameter type '(Process) → int' at lib/scheduled_process.dart:178:19 (argument_type_not_assignable).
[error] The argument type 'Converter<List<int>, String>' can't be assigned to the parameter type 'ChunkedConverter<dynamic, dynamic, List<int>, dynamic>' at lib/scheduled_process.dart:198:41 (argument_type_not_assignable).
[error] The argument type 'LineSplitter' can't be assigned to the parameter type 'ChunkedConverter' at lib/scheduled_process.dart:199:41 (argument_type_not_assignable).
[error] The return type 'Future' isn't a 'void', as defined by the method '_validateNow' at lib/src/descriptor/file_descriptor.dart:145:7 (return_of_invalid_type).
[hint] 'ChunkedConverter' is deprecated and shouldn't be used at lib/src/utils.dart:262:5 (deprecated_member_use).
[hint] 'expectAsync' is deprecated and shouldn't be used at lib/src/schedule.dart:227:29 (deprecated_member_use).
[warning] Unsafe implicit cast from 'Future<dynamic>' to 'Future<T>'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime at lib/src/task.dart:84:14 (strong_mode_down_cast_composite).
```

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #32 

Several issues to note during review:

* Schedule and TaskQueue take a type parameter. This is because TaskQueue.schedule is expected to take a function of T, the type that `task.runChild` returns a Future of. Hopefully this isn't like, an external, breaking change? If it is too invasive, let me know how else to fix. (Can maybe just use `as`, though dirty...)
* tossed the (deprecated) ChunkedConverter for Converter. 

Maybe others...

One more Strong mode issue remains. LineSplitter doesn't fit where it is... not sure how to fix right now.

### CODE REVIEW

File: lib/src/descriptor/file_descriptor.dart [hunk 1]
```diff
@@ -141,8 +141,9 @@ class _MatcherFileDescriptor extends FileDescriptor {
       : _isBinary = isBinary == true ? true : false,
         super._(name, <int>[]);
 
-  void _validateNow(List<int> actualContents) =>
+  void _validateNow(List<int> actualContents) {
       expect(
           _isBinary ? actualContents : new String.fromCharCodes(actualContents),
           _matcher);
+  }
```
Comment (nex3) [inline lib/src/descriptor/file_descriptor.dart]: This change shouldn't be necessary with the latest `test`. You may need to increment `scheduled_test`'s constraint to get it, though.

File: lib/src/schedule.dart [hunk 2]
```diff
@@ -17,26 +17,26 @@ import 'utils.dart';
 ///
 /// This has two task queues: [tasks] and [onComplete]. It also provides
 /// visibility into the current state of the schedule.
-class Schedule {
+class Schedule<T> {
```
Comment (nex3) [inline lib/src/schedule.dart]: This type is wrong. A schedule doesn't always use the same return value for every task—task return values are typed separately for each call to `schedule()`. So neither `Schedule` nor `TaskQueue` should have type parameters.

File: lib/scheduled_test.dart [hunk 3]
```diff
@@ -174,8 +174,8 @@ void tearDownAll(body()) {
 /// on the next event loop iteration rather than adding it to a queue. The
 /// current task will not complete until [fn] (and any [Future] it returns) has
 /// finished running.
-Future/*<T>*/ schedule/*<T>*/(/*=T*/ fn(), [String description]) =>
-  currentSchedule.tasks.schedule(fn, description);
+Future<T> schedule<T>(T fn(), [String description]) =>
```
Comment (nex3) [inline lib/scheduled_test.dart]: Make sure the SDK version only allows versions that support uncommented generic methods.

File: lib/src/task.dart [hunk 4]
```diff
@@ -94,8 +94,8 @@ class Task<T> {
   /// Run [fn] as a child of this task. Returns a Future that will complete with
   /// the result of the child task. This task will not complete until [fn] has
   /// finished.
-  Future/*<S>*/ runChild/*<S>*/(/*=S*/ fn(), String description) {
-    var task = new Task/*<S>*/._child(fn, description, this);
+  Future<T> runChild(TaskBody fn, String description) {
```
Comment (nex3) [inline lib/src/task.dart]: The original type parameter was correct. `Task.runChild()` can return a different type than the `Task` itself returned.

**Review by nex3 — CHANGES_REQUESTED** [review]

File: lib/scheduled_test.dart (hunk 3 above)
Comment (srawlins) [reply lib/scheduled_test.dart]: Done. 1.22.0 required for FutureOr type.

File: lib/src/descriptor/file_descriptor.dart (hunk 1 above)
Comment (srawlins) [reply lib/src/descriptor/file_descriptor.dart]: Done! Thanks Natalie for that catch.

File: lib/src/schedule.dart (hunk 2 above)
Comment (srawlins) [reply lib/src/schedule.dart]: Done

File: lib/src/task.dart (hunk 4 above)
Comment (srawlins) [reply lib/src/task.dart]: Done

**Comment by srawlins** [comment]
Thanks Natalie. If you have a hint on the LineSplitter issue, I'll take it!

Also let me know if I need to bump the CHANGELOG or the version in pubspec.

File: lib/src/task.dart [hunk 5]
```diff
@@ -94,8 +94,8 @@ class Task<T> {
   /// Run [fn] as a child of this task. Returns a Future that will complete with
   /// the result of the child task. This task will not complete until [fn] has
   /// finished.
-  Future/*<S>*/ runChild/*<S>*/(/*=S*/ fn(), String description) {
-    var task = new Task/*<S>*/._child(fn, description, this);
+  Future<S> runChild<S>(TaskBody<S> fn, String description) {
```
Comment (nex3) [inline lib/src/task.dart]: I prefer to avoid using function types in public locations if possible, since it makes the documentation less direct.

**Review by nex3 — CHANGES_REQUESTED** [review]
> Thanks Natalie. If you have a hint on the LineSplitter issue, I'll take it!

What's the error you're seeing?

> Also let me know if I need to bump the CHANGELOG or the version in pubspec.

Yes, please bump to the next minor version, and please add a CHANGELOG note about the strong mode fixes and about supporting new `test` APIs.

**Comment by srawlins** [comment]
Sorry, the new LineSplitter error is a bit different, since removing ChunkedConverter:

> [error] The argument type 'LineSplitter' can't be assigned to the parameter type 'Converter<String, dynamic>' at lib/scheduled_process.dart:199:41 (argument_type_not_assignable).

**Comment by nex3** [comment]
You might need to use `LineSplitter.bind()` instead of `.transform(LineSplitter)` somewhere...

File: lib/src/task.dart (hunk 5 above)
Comment (srawlins) [reply lib/src/task.dart]: Done.

**Comment by srawlins** [comment]
OK, I'll hold off on that fix.

**Comment by nex3** [comment]
Don't forget the pubspec + changelog!

**Comment by srawlins** [comment]
Done

**Comment by nex3** [comment]
Thanks!
